### ISSUE TITLE
WakeupException fails a commit to the kafka

### ISSUE THREAD

**Issue by vladimir-popov** [dokwork/easy-kafka#1]
Some times stop polling failed commit:
```
[info]   Scenario: Repeated poll should not receive previously handled messages *** FAILED ***
[info]   org.apache.kafka.common.errors.WakeupException:
[info]   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.clientPoll(ConsumerNetworkClient.java:324)
[info]   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:213)
[info]   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:193)
[info]   at org.apache.kafka.clients.consumer.internals.ConsumerNetworkClient.poll(ConsumerNetworkClient.java:163)
[info]   at org.apache.kafka.clients.consumer.internals.ConsumerCoordinator.commitOffsetsSync(ConsumerCoordinator.java:358)
[info]   at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:968)
[info]   at org.apache.kafka.clients.consumer.KafkaConsumer.commitSync(KafkaConsumer.java:936)
[info]   at ru.dokwork.easy.kafka.KafkaConsumer$PollingImpl.$anonfun$commitIfNeed$1(KafkaConsumer.scala:122)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at scala.concurrent.Future$.$anonfun$apply$1(Future.scala:655)
[info]   ...
```

**Comment by vladimir-popov** [comment]
fixed by https://github.com/dokwork/easy-kafka/pull/2
